# ----------------------------------------------------- #
# MAG ANNOTATION WORKFLOW
# ----------------------------------------------------- #


# load config
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/prok.smk"
include: "rules/euk.smk"


# feedback messages
# -----------------------------------------------------
onstart:
    print("\n--- MAG Annotation Pipeline: Started ---\n")


onsuccess:
    print("\n--- Workflow finished successfully! ---\n")


onerror:
    print("\n--- ERROR: Check the logs in the logs/ folder ---\n")


# target rules
# -----------------------------------------------------
prok_samples = samples[samples["domain"] == "prok"].index.tolist()
euk_mag_samples = samples[
    (samples["domain"] == "euk") & (samples["genome_type"] == "mag")
].index.tolist()
euk_isolate_samples = samples[
    (samples["domain"] == "euk") & (samples["genome_type"] == "isolate")
].index.tolist()
if not config.get("funannotate2", {}).get("enabled", True):
    euk_isolate_samples = []


rule all:
    default_target: True
    input:
        expand("results/bakta/{sample}/{sample}.faa", sample=prok_samples),
        expand(
            "results/recognizer/prok/{sample}/reCOGnizer_results.tsv",
            sample=prok_samples,
        ),
        expand("results/upimapi/{sample}/uniprotinfo.tsv", sample=prok_samples),
        expand(
            "results/recognizer/euk/{sample}/reCOGnizer_results.tsv",
            sample=euk_mag_samples,
        ),
        expand(
            "results/funannotate2/{sample}/annotate.done",
            sample=euk_isolate_samples,
        ),
        # "results/gtdbtk"
