# ====================
# General Input
# ====================
sample_sheet: "config/samples.tsv"

directory_mode:
  enabled: false
  sample: ""
  prok_bins_dir: ""
  euk_bins_dir: ""
  checkm2_report: ""
  eukcc_report: ""

# ====================
# Quality Filtering
# ====================
qa_filter:
  enabled: false
  min_completeness: 50.0
  max_contamination: 10.0
  checkm2_reports: []
  eukcc_reports: []
  missing_sample: "error"

# ====================
# Prokaryotic Annotation
# ====================

# --------------------
# Prodigal
# --------------------
prodigal:
  extra: "-p meta -f gff"

# --------------------
# Bakta
# --------------------
bakta:
  db: ""
  extra: ""

# --------------------
# GTDB-Tk
# --------------------
gtdbtk:
  enabled: false
  data_dir: ""
  extra: ""

# --------------------
# reCOGnizer Prokaryotic
# --------------------
recognizer_prok:
  resources_dir: ""
  extra: ""

# --------------------
# UPIMAPI
# --------------------
upimapi:
  db: "swissprot"
  db_custom: ""
  resources_dir: ""
  extra: ""
  skip_db_check_if_exists: true

# ====================
# Eukaryotic Annotation
# ====================

# --------------------
# MetaEuk
# --------------------
metaeuk:
  db: ""
  extra: ""

# --------------------
# reCOGnizer Eukaryotic
# --------------------
recognizer_euk:
  resources_dir: ""
  custom_db: ""
  extra: ""

# --------------------
# Funannotate2
# --------------------
funannotate2:
  enabled: true
  db_dir: ""
  install_db: true
  databases:
    - all
  extra_install: ""
  species: ""
  strain: ""
  params: ""
  pretrained: ""
  extra_clean: ""
  extra_train: ""
  extra_predict: ""
  extra_annotate: ""

# ====================
# Computational Resources
# ====================
threads:
  high: 16
  medium: 8
  low: 1
