sample_sheet: "config/samples.tsv"

qa_filter:
  enabled: false
  min_completeness: 50.0
  max_contamination: 10.0
  checkm2_reports: []
  eukcc_reports: []
  missing_sample: "error"

prodigal:
  extra: "-p meta -f gff"

bakta:
  db: "resources/bakta_db"
  extra: ""

gtdbtk:
  data_dir: "resources/gtdbtk_db"
  extra: ""

metaeuk:
  db: "resources/metaeuk_db/uniprot_db"
  extra: ""

recognizer:
  resources_dir: "resources/recognizer_db"
  extra: ""
  euk_custom_db: ""
  euk_extra: ""

upimapi:
  db: "swissprot"
  db_custom: ""
  resources_dir: "resources/upimapi_db"
  extra: ""
  skip_db_check_if_exists: true

threads:
  high: 16
  medium: 8
  low: 1
